document.addEventListener('DOMContentLoaded', function() {
    generateRandomTip();
});

const tips = [
    "First God",
    "Vamos de paseo π π π",
    "Are you sad? Don't be sad.",
    "Back to the future is the best movie.",
    "Back to the future II is the second best movie.",
    "-.-",
    ":v",
    "Another book suggestion: Shadows of the Mind.",
    "Another book suggestion: Outliers.",
    "Another book suggestion: Through the Glass Ceiling to the Stars.",
    "Huang says don't learn to code",
    "Trust me, I' lying",
    "a",
    "Buy me a book",
    "If I write a message on a sticky note, go back in time and give it to my past self with instructions to give to my future self for the purpose of sending it back in time again, I've effectively erased the creation of the first sticky note. It now exists always, yet was never created.",
    "This sentence is false",
    "Creo.",
    "Let me go to have lunch first.",
    "Infinito positivo no contable elevado al ...",
    "I need a cup of coffee before I make coffee.",
    "If Pinocchio says his nose will grow, will it grow?",
    "Never gonna give you up, never gonna let you down",
    "My advice is not to follow my advice",
    "If multiverse theory is true, and there are infinite universes with infinite possibilities, then there is one where the theory is false.",
    "A circle is randomly generated by sampling two points uniformly and independently from the interior of a square and using these points to determine its diameter. What is the probability that the circle has a part of it that is off the square? Give your answer in exact terms.",
    "Find x,y,z for x^4 + y^4 = z^4. It's easy!",
    "Demonstration is left as an exercise to the reader.",
    "GO CARDINALS!",
    "Are you tired? Don't be tired.",
    "Find all triples of positive integers pa, b, pq with p prime and a^p = b! + p.",
    "Prove that 5^n - 3^n is not divisible by 2^n + 65 for any positive integer n.",
    "Remember to stay hydrated!"
    "._."
    "if the life gives you spheres, use spherical coordinares."
    

    // Add more tips as needed
];

function generateRandomTip() {
    const tipContainer = document.getElementById('tip-container');
    const randomIndex = Math.floor(Math.random() * tips.length);
    const randomTip = tips[randomIndex];

    tipContainer.innerHTML = `<p class="tip"># ${randomIndex + 1}</p><p>${randomTip}</p>`;
}
